(in-package :cl-user)

(cl:defpackage #:cl-pango
  (:nicknames :pango)
  (:use #:cl)
  (:export

   #:with-context-from-surface
   #:clear-cairo-context
   #:print-raw-text
   #:print-text
   #:print-with-attributes
   #:get-size-for-text
   #:with-paragraph
   #:with-pango-object
   #:with-pango-objects
   #:with-attribute-list
   #:add-foreground-color-attribute
   #:add-background-color-attribute
   #:add-size-attribute
   #:add-absolute-size-attribute
   #:add-weight-attribute
   #:add-family-attribute
   #:add-style-attribute
   #:add-variant-attribute
   #:add-stretch-attribute
   #:add-stretch-attribute
   #:add-strikethrough-attribute
   #:add-strikethrough-color-attribute
   #:add-underline-attribute
   #:add-underline-color-attribute
   #:add-rise-attribute
   #:add-letter-spacing-attribute
   
   #:g_object_unref
   #:pangocontext
   #:pangoitem
   #:pangoanalysis
   #:gslist
   #:glist
   #:pangologattr
   #:pangolayoutline
   #:pango_itemize
   #:pango_itemize_with_base_dir
   #:pango_item_free
   #:pango_item_copy
   #:pango_item_new
   #:pango_item_split
   #:pango_reorder_items
   #:pango_context_new
   #:pango_context_set_font_map
   #:pango_context_get_font_map
   #:pango_context_get_font_description
   #:pango_context_set_font_description
   #:pango_context_get_language
   #:pango_context_set_language
   #:pango_context_get_base_dir
   #:pango_context_set_base_dir
   #:pango_context_get_base_gravity
   #:pango_context_set_base_gravity
   #:pango_context_get_gravity
   #:pango_context_get_gravity_hint
   #:pango_context_set_gravity_hint
   #:pango_context_get_matrix
   #:pango_context_set_matrix
   #:pango_context_load_font
   #:pango_context_load_fontset
   #:pango_context_get_metrics
   #:pango_context_list_families
   #:pango_break
   #:pango_get_log_attrs
   #:pango_find_paragraph_boundary
   #:pango_default_break
   #:pango_shape
   #:pango_scale
   #:pango_units_to_double
   #:pango_units_from_double
   #:pangorectangle
   #:pango_extents_to_pixels
   #:pangomatrix
   #:pango_matrix_copy
   #:pango_matrix_free
   #:pango_matrix_translate
   #:pango_matrix_scale
   #:pango_matrix_rotate
   #:pango_matrix_concat
   #:pango_matrix_transform_point
   #:pango_matrix_transform_distance
   #:pango_matrix_transform_rectangle
   #:pango_matrix_transform_pixel_rectangle
   #:pango_matrix_get_font_scale_factor
   #:pangoglyph
   #:pangoglyphinfo
   #:pangoglyphgeometry
   #:pangoglyphunit
   #:pangoglyphvisattr
   #:pangoglyphstring
   #:pangoglyphitemiter
   #:pango_glyph_string_new
   #:pango_glyph_string_copy
   #:pango_glyph_string_set_size
   #:pango_glyph_string_free
   #:pango_glyph_string_extents
   #:pango_glyph_string_extents_range
   #:pango_glyph_string_get_width
   #:pango_glyph_string_index_to_x
   #:pango_glyph_string_x_to_index
   #:pango_glyph_string_get_logical_widths
   #:pango_glyph_item_copy
   #:pango_glyph_item_free
   #:pango_glyph_item_split
   #:pango_glyph_item_apply_attrs
   #:pango_glyph_item_letter_space
   #:pango_glyph_item_get_logical_widths
   #:pango_glyph_item_iter_copy
   #:pango_glyph_item_iter_free
   #:pango_glyph_item_iter_init_start
   #:pango_glyph_item_iter_init_end
   #:pango_glyph_item_iter_next_cluster
   #:pango_glyph_item_iter_prev_cluster
   #:pangofontdescription
   #:pangofontmetrics
   #:pangofontsetclass
   #:pangofontmapclass
   #:pango_font_description_new
   #:pango_font_description_copy
   #:pango_font_description_copy_static
   #:pango_font_description_hash
   #:pango_font_description_equal
   #:pango_font_description_free
   #:pango_font_descriptions_free
   #:pango_font_description_set_family
   #:pango_font_description_set_family_static
   #:pango_font_description_get_family
   #:pango_font_description_set_style
   #:pango_font_description_get_style
   #:pango_font_description_set_variant
   #:pango_font_description_get_variant
   #:pango_font_description_set_weight
   #:pango_font_description_get_weight
   #:pango_font_description_set_stretch
   #:pango_font_description_get_stretch
   #:pango_font_description_set_size
   #:pango_font_description_get_size
   #:pango_font_description_set_absolute_size
   #:pango_font_description_get_size_is_absolute
   #:pango_font_description_set_gravity
   #:pango_font_description_get_gravity
   #:pango_font_description_get_set_fields
   #:pango_font_description_unset_fields
   #:pango_font_description_merge
   #:pango_font_description_merge_static
   #:pango_font_description_better_match
   #:pango_font_description_from_string
   #:pango_font_description_to_string
   #:pango_font_description_to_filename
   #:pango_font_metrics_ref
   #:pango_font_metrics_unref
   #:pango_font_metrics_get_ascent
   #:pango_font_metrics_get_descent
   #:pango_font_metrics_get_approximate_char_width
   #:pango_font_metrics_get_approximate_digit_width
   #:pango_font_metrics_get_underline_thickness
   #:pango_font_metrics_get_underline_position
   #:pango_font_metrics_get_strikethrough_thickness
   #:pango_font_metrics_get_strikethrough_position
   #:pangofont
   #:pango_font_find_shaper
   #:pango_font_describe
   #:pango_font_describe_with_absolute_size
   #:pango_font_get_coverage
   #:pango_font_get_glyph_extents
   #:pango_font_get_metrics
   #:pango_font_get_font_map
   #:pangofontfamily
   #:pango_font_family_get_name
   #:pango_font_family_is_monospace
   #:pango_font_family_list_faces
   #:pangofontface
   #:pango_font_face_get_face_name
   #:pango_font_face_list_sizes
   #:pango_font_face_describe
   #:pango_font_face_is_synthesized
   #:pangofontmap
   #:pango_font_map_create_context
   #:pango_font_map_load_font
   #:pango_font_map_load_fontset
   #:pango_font_map_list_families
   #:pango_font_map_get_shape_engine_type
   #:pangofontset
   #:pango_fontset_get_font
   #:pango_fontset_get_metrics
   #:pangofontsetforeachfunc
   #:pango_fontset_foreach
   #:pangofontsetsimple
   #:pango_fontset_simple_new
   #:pango_fontset_simple_append
   #:pango_fontset_simple_size
   #:pangoattrclass
   #:pangoattribute
   #:pango_attr_index_from_text_beginning
   #:pango_attr_index_to_text_end
   #:pangoattrstring
   #:pangoattrlanguage
   #:pangoattrcolor
   #:pangoattrint
   #:pangoattrfloat
   #:pangoattrfontdesc
   #:pangoattrshape
   #:pangoattrsize
   #:pangocolor
   #:pango_parse_markup
   #:pango_attr_type_register
   #:pango_attr_type_get_name
   #:pango_attribute_init
   #:pango_attribute_copy
   #:pango_attribute_equal
   #:pango_attribute_destroy
   #:pango_attr_language_new
   #:pango_attr_family_new
   #:pango_attr_style_new
   #:pango_attr_variant_new
   #:pango_attr_stretch_new
   #:pango_attr_weight_new
   #:pango_attr_size_new
   #:pango_attr_size_new_absolute
   #:pango_attr_font_desc_new
   #:pango_attr_foreground_new
   #:pango_attr_background_new
   #:pango_attr_strikethrough_new
   #:pango_attr_strikethrough_color_new
   #:pango_attr_underline_new
   #:pango_attr_underline_color_new
   #:pango_attr_shape_new
   #:pango_attr_shape_new_with_data
   #:pangoattrdatacopyfunc
   #:pango_attr_scale_new
   #:pango_scale_xx_small
   #:pango_scale_x_small
   #:pango_scale_small
   #:pango_scale_medium
   #:pango_scale_large
   #:pango_scale_x_large
   #:pango_scale_xx_large
   #:pango_attr_rise_new
   #:pango_attr_letter_spacing_new
   #:pango_attr_fallback_new
   #:pango_attr_gravity_new
   #:pango_attr_gravity_hint_new
   #:pango_color_parse
   #:pango_color_copy
   #:pango_color_free
   #:pango_color_to_string
   #:pangoattrlist
   #:pango_attr_list_new
   #:pango_attr_list_ref
   #:pango_attr_list_unref
   #:pango_attr_list_copy
   #:pango_attr_list_insert
   #:pango_attr_list_insert_before
   #:pango_attr_list_change
   #:pango_attr_list_splice
   #:pango_attr_list_filter
   #:pangoattrfilterfunc
   #:pango_attr_list_get_iterator
   #:pangoattriterator
   #:pango_attr_iterator_copy
   #:pango_attr_iterator_next
   #:pango_attr_iterator_range
   #:pango_attr_iterator_get
   #:pango_attr_iterator_get_font
   #:pango_attr_iterator_get_attrs
   #:pango_attr_iterator_destroy
   #:pangotabarray
   #:pango_tab_array_new
   #:pango_tab_array_new_with_positions
   #:pango_tab_array_copy
   #:pango_tab_array_free
   #:pango_tab_array_get_size
   #:pango_tab_array_resize
   #:pango_tab_array_set_tab
   #:pango_tab_array_get_tab
   #:pango_tab_array_get_tabs
   #:pango_tab_array_get_positions_in_pixels
   #:pangolayout
   #:pangolayoutiter
   #:pangoglyphitem
   #:pango_layout_new
   #:pango_layout_copy
   #:pango_layout_get_context
   #:pango_layout_context_changed
   #:pango_layout_set_text
   #:pango_layout_get_text
   #:pango_layout_set_markup
   #:pango_layout_set_markup_with_accel
   #:pango_layout_set_attributes
   #:pango_layout_get_attributes
   #:pango_layout_set_font_description
   #:pango_layout_get_font_description
   #:pango_layout_set_width
   #:pango_layout_get_width
   #:pango_layout_set_height
   #:pango_layout_get_height
   #:pango_layout_set_wrap
   #:pango_layout_get_wrap
   #:pango_layout_is_wrapped
   #:pango_layout_set_ellipsize
   #:pango_layout_get_ellipsize
   #:pango_layout_is_ellipsized
   #:pango_layout_set_indent
   #:pango_layout_get_indent
   #:pango_layout_get_spacing
   #:pango_layout_set_spacing
   #:pango_layout_set_justify
   #:pango_layout_get_justify
   #:pango_layout_set_auto_dir
   #:pango_layout_get_auto_dir
   #:pango_layout_set_alignment
   #:pango_layout_get_alignment
   #:pango_layout_set_tabs
   #:pango_layout_get_tabs
   #:pango_layout_set_single_paragraph_mode
   #:pango_layout_get_single_paragraph_mode
   #:pango_layout_get_unknown_glyphs_count
   #:pango_layout_get_log_attrs
   #:pango_layout_index_to_pos
   #:pango_layout_index_to_line_x
   #:pango_layout_xy_to_index
   #:pango_layout_get_cursor_pos
   #:pango_layout_move_cursor_visually
   #:pango_layout_get_extents
   #:pango_layout_get_pixel_extents
   #:pango_layout_get_size
   #:pango_layout_get_pixel_size
   #:pango_layout_get_baseline
   #:pango_layout_get_line_count
   #:pango_layout_get_line
   #:pango_layout_get_line_readonly
   #:pango_layout_get_lines
   #:pango_layout_get_lines_readonly
   #:pango_layout_get_iter
   #:pango_layout_iter_copy
   #:pango_layout_iter_free
   #:pango_layout_iter_next_run
   #:pango_layout_iter_next_char
   #:pango_layout_iter_next_cluster
   #:pango_layout_iter_next_line
   #:pango_layout_iter_at_last_line
   #:pango_layout_iter_get_index
   #:pango_layout_iter_get_baseline
   #:pango_layout_iter_get_run
   #:pango_layout_iter_get_run_readonly
   #:pango_layout_iter_get_line
   #:pango_layout_iter_get_line_readonly
   #:pango_layout_iter_get_layout
   #:pango_layout_iter_get_char_extents
   #:pango_layout_iter_get_cluster_extents
   #:pango_layout_iter_get_run_extents
   #:pango_layout_iter_get_line_yrange
   #:pango_layout_iter_get_line_extents
   #:pango_layout_iter_get_layout_extents
   #:pango_layout_line_ref
   #:pango_layout_line_unref
   #:pango_layout_line_get_extents
   #:pango_layout_line_get_pixel_extents
   #:pango_layout_line_index_to_x
   #:pango_layout_line_x_to_index
   #:pango_layout_line_get_x_ranges
   #:pangoscriptiter
   #:pango_script_for_unichar
   #:pango_script_get_sample_language
   #:pango_script_iter_new
   #:pango_script_iter_get_range
   #:pango_script_iter_next
   #:pango_script_iter_free
   #:pangolanguage
   #:pango_language_from_string
   #:pango_language_to_string
   #:pango_language_matches
   #:pango_language_includes_script
   #:pango_language_get_scripts
   #:pango_language_get_default
   #:pango_language_get_sample_string
   #:pango_unichar_direction
   #:pango_find_base_dir
   #:pango_get_mirror_char
   #:pango_bidi_type_for_unichar
   #:pango_gravity_get_for_matrix
   #:pango_gravity_get_for_script
   #:pango_gravity_get_for_script_and_width
   #:pango_gravity_to_rotation
   #:pangocairofont
   #:pangocairofontmap
   #:cairo_t
   #:cairo_font_type_t
   #:pango_cairo_font_map_get_default
   #:pango_cairo_font_map_set_default
   #:pango_cairo_font_map_new
   #:pango_cairo_font_map_new_for_font_type
   #:pango_cairo_font_map_get_font_type
   #:pango_cairo_font_map_set_resolution
   #:pango_cairo_font_map_get_resolution
   #:pango_cairo_font_map_create_context
   #:pango_cairo_font_get_scaled_font
   #:pango_cairo_context_set_resolution
   #:pango_cairo_context_get_resolution
   #:pango_cairo_context_set_font_options
   #:pango_cairo_context_get_font_options
   #:pangocairoshaperendererfunc
   #:pango_cairo_context_set_shape_renderer
   #:pango_cairo_context_get_shape_renderer
   #:pango_cairo_create_context
   #:pango_cairo_update_context
   #:pango_cairo_create_layout
   #:pango_cairo_update_layout
   #:pango_cairo_show_glyph_string
   #:pango_cairo_show_glyph_item
   #:pango_cairo_show_layout_line
   #:pango_cairo_show_layout
   #:pango_cairo_show_error_underline
   #:pango_cairo_glyph_string_path
   #:pango_cairo_layout_line_path
   #:pango_cairo_layout_path
   #:pango_cairo_error_underline_path
   #:ezcolor
   #:get-line-from-position
   #:get-layout-size
   #:get-layout-extents
   #:get-layout-line-extents
   #:get-layout-lines-data
   #:move-cursor-visually
   #:get-layout-lines
   #:get-previous-line
   #:layout-line-index-to-x
   #:layout-line-x-to-index
   #:get-cursor-pos
   #:list-font-families
   #:list-font-family-names
   #:list-font-faces
   ))
